# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0573636ecd1b467fcc666570a949d0bb1a3067c7496a780685ddca7574c73ac00554ec8c910298ce649997b7d6ca9b6845e7eb3ef3654d908ac4a2e17b70b8f7

test:
  secret_key_base: f246777a2d473d807568a138ad8541274809555bc996d842f79732003e63a3841b63b267fed43f253a40357bf18ac66ea3789d75493ec427b12cab03d17d9a74

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
