# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29e9e863f3bfd80e63ad14420db97ee308031202e3789aca003b7b95883210930d8151709c51fb4ea9c61046c177cf93678980116d2edca78548b572b6053a45

test:
  secret_key_base: e8821fd726262375b96f8f739806f210448077d80816c762a720d9bff55f3f6b01358c62324b932de0f3740e078152ed44e923c5a2eb59f0193a8e702eaa6831

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
