# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a97d9c4b7d8ea3ca984b68b83973ed05af63aa64f01a9772d239fec7916a08077d93029d87c656c61f7d1ad7165cecf5521c9c6256085372b77cea6970b71c5

test:
  secret_key_base: a173bf6d82123e9f78e3f58699650882805fac77afc4c27d8d81d4f1dc3ce6c34352b1661afc5dd3d536f9927d97cf81d5b455fe6e1bfe61fc779d55250fa553

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
