# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b0ae75d60c57f2cca8739cbda64b5ebcc2aca4f23b90afb2af212925657dc747bf8160e9a6c8f523bfa86f84ee78f633df3228ce7621b0375d8dae4bab27e145

test:
  secret_key_base: a43a9f1d2956531b0b4400bd1a8000615dc0c5d4e33b290ae61d1b57b55546abd1febe36af0fec880d06a5cc01042f4fbd6c9ec3b7f54d9d6cbfb7f18d28c323

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
